development:
  adapter: postgresql
  encoding: unicode
  database: rails_api_development
  host: localhost
  port: 5432
  username: root
  password: root

production:
  adapter: postgresql
  encoding: unicode
  database: rails_api_development
  pool: 5
  username: postgres
  password: root
  host: localhost  